---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[plexapp::default]
    attributes:
