name             'plexapp'
maintainer       'Joshua Timberman'
maintainer_email 'cookbooks@housepub.org'
license          'Apache 2.0'
description      'Installs and configures Plex media server'
version          '1.0.0'

supports 'ubuntu'
supports 'fedora'
supports 'centos'
